// GENERATED from design-system/tokens.json. Regenerate, do not edit this file.
package com.pocketshell.designpreview

import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Typography
import androidx.compose.material3.Shapes
import androidx.compose.material3.darkColorScheme
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.runtime.Composable
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.TextStyle
import androidx.compose.ui.text.PlatformTextStyle
import androidx.compose.ui.text.font.FontFamily
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp

object PsTokens {
    val background = Color(0xFF10171E)
    val surface = Color(0xFF19222B)
    val surfaceRaised = Color(0xFF222D38)
    val text = Color(0xFFF0F3F7)
    val secondary = Color(0xFFA6B2C1)
    val muted = Color(0xFF92A0B0)
    val divider = Color(0xFF2B3946)
    val inputBorder = Color(0xFF64778A)
    val accent = Color(0xFF53D8EC)
    val onAccent = Color(0xFF082027)
    val positive = Color(0xFF5CDF89)
    val warning = Color(0xFFE6BC78)
    val error = Color(0xFFF3A1A1)
    val terminal = Color(0xFF0B1117)
    val scrim = Color(0x99000000)
    val touchMin = 48.dp
    val buttonMin = 56.dp
    val fieldMin = 56.dp
    val workspaceRowMin = 64.dp
    val listRowMin = 56.dp
    val rowPadV = 8.dp
    val rowPadH = 20.dp
    val chipPadV = 6.dp
    val chipPadH = 10.dp
    val sectionGap = 24.dp
    val treeIndent = 16.dp
    val icon = 24.dp
    val metadataIcon = 18.dp
    val screenGutter = 20.dp
    val systemTopPreview = 28.dp
    val systemBottomPreview = 24.dp
    val spaceXs = 4.dp
    val spaceSm = 8.dp
    val spaceMd = 12.dp
    val spaceLg = 16.dp
    val spaceXl = 20.dp
    val spaceXxl = 24.dp
    val badgeRadius = 4.dp
    val chipRadius = 8.dp
    val fieldRadius = 12.dp
    val buttonRadius = 12.dp
    val cardRadius = 12.dp
    val sheetRadius = 24.dp
    val screenType = TextStyle(
        fontFamily = FontFamily.SansSerif,
        fontSize = 20.sp, lineHeight = 26.sp,
        fontWeight = FontWeight(700),
        platformStyle = PlatformTextStyle(includeFontPadding = false),
    )
    val workspaceType = TextStyle(
        fontFamily = FontFamily.SansSerif,
        fontSize = 16.sp, lineHeight = 22.sp,
        fontWeight = FontWeight(600),
        platformStyle = PlatformTextStyle(includeFontPadding = false),
    )
    val titleType = TextStyle(
        fontFamily = FontFamily.SansSerif,
        fontSize = 16.sp, lineHeight = 22.sp,
        fontWeight = FontWeight(600),
        platformStyle = PlatformTextStyle(includeFontPadding = false),
    )
    val bodyType = TextStyle(
        fontFamily = FontFamily.SansSerif,
        fontSize = 14.sp, lineHeight = 20.sp,
        fontWeight = FontWeight(400),
        platformStyle = PlatformTextStyle(includeFontPadding = false),
    )
    val metadataType = TextStyle(
        fontFamily = FontFamily.SansSerif,
        fontSize = 11.sp, lineHeight = 16.sp,
        fontWeight = FontWeight(400),
        platformStyle = PlatformTextStyle(includeFontPadding = false),
    )
    val labelType = TextStyle(
        fontFamily = FontFamily.SansSerif,
        fontSize = 11.sp, lineHeight = 16.sp,
        fontWeight = FontWeight(500),
        platformStyle = PlatformTextStyle(includeFontPadding = false),
    )
    val buttonType = TextStyle(
        fontFamily = FontFamily.SansSerif,
        fontSize = 14.sp, lineHeight = 20.sp,
        fontWeight = FontWeight(600),
        platformStyle = PlatformTextStyle(includeFontPadding = false),
    )
    val terminalType = TextStyle(
        fontFamily = FontFamily.Monospace,
        fontSize = 11.sp, lineHeight = 16.sp,
        fontWeight = FontWeight(400),
        platformStyle = PlatformTextStyle(includeFontPadding = false),
    )
    val bodyDenseType = TextStyle(
        fontFamily = FontFamily.SansSerif,
        fontSize = 13.sp, lineHeight = 18.sp,
        fontWeight = FontWeight(400),
        platformStyle = PlatformTextStyle(includeFontPadding = false),
    )
    val bodyMonoType = TextStyle(
        fontFamily = FontFamily.Monospace,
        fontSize = 13.sp, lineHeight = 18.sp,
        fontWeight = FontWeight(400),
        platformStyle = PlatformTextStyle(includeFontPadding = false),
    )
    val labelMonoType = TextStyle(
        fontFamily = FontFamily.Monospace,
        fontSize = 11.sp, lineHeight = 14.sp,
        fontWeight = FontWeight(400),
        platformStyle = PlatformTextStyle(includeFontPadding = false),
    )
}

@Composable
fun PocketShellQuietTheme(content: @Composable () -> Unit) {
    MaterialTheme(
        colorScheme = darkColorScheme(
            primary = PsTokens.accent, onPrimary = PsTokens.onAccent,
            primaryContainer = PsTokens.surfaceRaised, onPrimaryContainer = PsTokens.text,
            secondary = PsTokens.secondary, onSecondary = PsTokens.background,
            secondaryContainer = PsTokens.surfaceRaised, onSecondaryContainer = PsTokens.text,
            tertiary = PsTokens.secondary, onTertiary = PsTokens.background,
            background = PsTokens.background, onBackground = PsTokens.text,
            surface = PsTokens.surface, onSurface = PsTokens.text,
            surfaceVariant = PsTokens.surfaceRaised, onSurfaceVariant = PsTokens.secondary,
            surfaceTint = Color.Transparent,
            outline = PsTokens.inputBorder, outlineVariant = PsTokens.divider,
            error = PsTokens.error, onError = PsTokens.background,
            errorContainer = PsTokens.surface, onErrorContainer = PsTokens.error,
            scrim = Color.Black,
        ),
        typography = Typography(
            headlineLarge = PsTokens.screenType,
            headlineSmall = PsTokens.titleType,
            titleLarge = PsTokens.workspaceType,
            titleMedium = PsTokens.bodyType,
            bodyLarge = PsTokens.bodyType,
            bodyMedium = PsTokens.metadataType,
            labelLarge = PsTokens.buttonType,
            labelMedium = PsTokens.labelType,
        ),
        shapes = Shapes(
            small = RoundedCornerShape(PsTokens.fieldRadius),
            medium = RoundedCornerShape(PsTokens.buttonRadius),
            large = RoundedCornerShape(PsTokens.sheetRadius),
        ),
        content = content,
    )
}
