package com.pocketshell.core.storage.entity

import androidx.room.Entity
import androidx.room.Index
import androidx.room.PrimaryKey

/**
 * One row per audio recording that is queued for Whisper transcription
 * but has not yet succeeded — issue #180.
 *
 * The user can speak a long voice prompt over a flaky network (entering a
 * tunnel, a dropped wifi handoff, etc.) and the upload to Whisper might
 * fail mid-flight. Before this entity existed, the whole audio buffer was
 * dropped and the user had to re-record. This row, paired with the audio
 * bytes persisted on disk at [audioPath], lets the composer offer a retry
 * affordance without losing the recording.
 *
 * Why a separate audio file rather than a `BLOB` column:
 *
 * - A 60-second 16 kHz mono 16-bit WAV is ~1.9 MB. Holding that as a
 *   SQLite BLOB inflates the DB file and forces every list query to drag
 *   the payload through Room's marshalling. A regular file in the app's
 *   private storage (`filesDir/voice-pending/<uuid>.wav`) costs nothing
 *   at row-read time.
 * - The audio file lifetime is owned by [com.pocketshell.app.voice.PendingTranscriptionStore];
 *   the row is the index. If a file disappears the row becomes orphaned
 *   and the store deletes it on next reconciliation.
 *
 * Field semantics:
 *
 * - [id] is a stable UUID string. Reused as the basename of the audio
 *   file under `filesDir/voice-pending/<id>.wav`. Strings are used (not
 *   the autogenerated `Long`) so a crash between "audio file written"
 *   and "row inserted" can be reconciled on startup without ambiguity.
 * - [audioPath] is the absolute path to the persisted audio file. The
 *   store deletes the file and the row together on success / discard.
 * - [recordingTimestampMs] is the epoch-millis at which the recording
 *   stopped (i.e. the moment the user expected to see the transcript).
 *   Used for the "X minutes ago" hint in the list affordance and for
 *   ordering newest-first.
 * - [destinationContext] is a free-form discriminator for where the
 *   transcript was meant to go: `"composer"` for the prompt composer
 *   draft, `"inline-dictation"` for the key-bar mic, `"share-target"`
 *   for an external Voice share. The retry path treats every value
 *   identically today (transcript is appended to the composer draft);
 *   the column is recorded so future routing can be added without a
 *   migration.
 * - [retryCount] is the number of completed Whisper attempts that
 *   failed. Starts at `0` when the row is created (which is BEFORE the
 *   first Whisper call) and increments on each failure. Issue #180 caps
 *   this at 3; at the cap the UI offers Delete or Save-as-audio rather
 *   than another retry.
 * - [lastErrorMessage] is the user-facing string from the most recent
 *   Whisper failure (or `"No network"` for offline-queued rows). Null
 *   means the row has not yet been attempted (offline queue) or the
 *   error was cleared by a retry.
 * - [audioByteSize] is the size of the audio file in bytes, cached on
 *   the row so the list UI does not have to stat() every file. Used by
 *   the per-recording 10 MB cap check.
 * - [createdAtMs] is the epoch-millis at which the row was inserted.
 *   Distinct from [recordingTimestampMs] only when a row is re-queued
 *   (today they are always equal); kept separate so future "queued at"
 *   vs "spoken at" semantics can diverge without a migration.
 *
 * Indexed on [recordingTimestampMs] so the composer's list query
 * (newest-first) is a range scan rather than a sort.
 */
@Entity(
    tableName = "pending_transcriptions",
    indices = [
        Index(value = ["recordingTimestampMs"]),
    ],
)
data class PendingTranscriptionEntity(
    @PrimaryKey val id: String,
    val audioPath: String,
    val recordingTimestampMs: Long,
    val destinationContext: String,
    val retryCount: Int,
    val lastErrorMessage: String?,
    val audioByteSize: Long,
    val createdAtMs: Long,
) {
    companion object {
        /** Destination tag for the prompt composer draft. */
        const val DESTINATION_COMPOSER: String = "composer"

        /** Destination tag for the key-bar inline dictation surface. */
        const val DESTINATION_INLINE_DICTATION: String = "inline-dictation"

        /**
         * Maximum retry attempts before the UI hides the Retry button and
         * offers Delete / Save-as-audio instead. Matches the cap called
         * out in issue #180's acceptance criteria ("3-retry cap").
         */
        const val MAX_RETRY_ATTEMPTS: Int = 3
    }
}
