package com.pocketshell.next.sync

import java.nio.charset.StandardCharsets
import java.util.Base64
import org.json.JSONObject
import org.junit.Assert.assertEquals
import org.junit.Assert.assertNotEquals
import org.junit.Assert.assertThrows
import org.junit.Assert.assertTrue
import org.junit.Test
import org.junit.runner.RunWith
import org.robolectric.RobolectricTestRunner
import org.robolectric.annotation.Config

/**
 * [SyncCrypto] — the zero-knowledge half of settings sync (issue #2633).
 *
 * Mirrors the desktop app's `tests/unit/SyncCrypto.test.ts` case for case
 * (round-trip, fresh salt/IV per write, documented envelope shape, wrong
 * passphrase, tampered ciphertext, non-envelope/truncated blobs, bad salt
 * length, blob-controlled iteration bound, multi-byte plaintext) and adds the
 * two things a PORT needs that the original did not:
 *
 * - **PBKDF2 known-answer vectors.** The key derivation is hand-rolled here
 *   over explicit UTF-8 bytes precisely because the JCE's `PBEKeySpec` leaves
 *   the char→byte conversion to the provider. A drift there would produce a
 *   perfectly self-consistent Android build that cannot open a single desktop
 *   blob, and no round-trip test in this file would notice.
 * - **A real desktop-produced envelope.** `crossImplementationEnvelope` was
 *   generated by Node with the exact calls `SyncCrypto.ts` makes; decrypting it
 *   here is the only assertion that actually proves the wire format matches.
 *
 * Robolectric because [SyncCrypto] parses the envelope with `org.json`, which
 * is stubbed in the plain unit-test android.jar (same reason
 * `ReleaseCheckerTest` uses it).
 */
@RunWith(RobolectricTestRunner::class)
@Config(manifest = Config.NONE, sdk = [33])
class SyncCryptoTest {

    @Test
    fun `round-trips a plaintext`() {
        val envelope = SyncCrypto.encryptToEnvelope("""{"hosts":[]}""", "correct horse")
        assertEquals("""{"hosts":[]}""", SyncCrypto.decryptEnvelope(envelope, "correct horse"))
    }

    @Test
    fun `produces a fresh salt and IV per write`() {
        val a = JSONObject(SyncCrypto.encryptToEnvelope("same", "pw"))
        val b = JSONObject(SyncCrypto.encryptToEnvelope("same", "pw"))
        assertNotEquals(a.getString("salt"), b.getString("salt"))
        assertNotEquals(a.getString("iv"), b.getString("iv"))
    }

    @Test
    fun `emits the documented envelope shape`() {
        val fields = JSONObject(SyncCrypto.encryptToEnvelope("x", "pw"))
        assertEquals(1, fields.getInt("v"))
        assertEquals("pbkdf2-sha256", fields.getString("kdf"))
        assertEquals(SyncCrypto.KDF_ITERATIONS, fields.getInt("iter"))
        assertEquals(16, decode(fields.getString("salt")).size)
        assertEquals(12, decode(fields.getString("iv")).size)
        // ct is ciphertext + the 16-byte GCM tag, so longer than the tag alone.
        assertTrue(decode(fields.getString("ct")).size > 16)
    }

    @Test
    fun `rejects the wrong passphrase`() {
        val envelope = SyncCrypto.encryptToEnvelope("secret", "right")
        val error = assertThrows(SyncCryptoError::class.java) {
            SyncCrypto.decryptEnvelope(envelope, "wrong")
        }
        // The message must not claim to know WHICH failure it was: GCM cannot
        // distinguish a wrong passphrase from a tampered blob.
        assertEquals("decryption failed — wrong passphrase or corrupted blob", error.message)
    }

    @Test
    fun `rejects a tampered ciphertext`() {
        val fields = JSONObject(SyncCrypto.encryptToEnvelope("secret", "pw"))
        val ct = decode(fields.getString("ct"))
        ct[0] = (ct[0].toInt() xor 0x01).toByte()
        fields.put("ct", Base64.getEncoder().encodeToString(ct))
        assertThrows(SyncCryptoError::class.java) {
            SyncCrypto.decryptEnvelope(fields.toString(), "pw")
        }
    }

    @Test
    fun `rejects a tampered auth tag`() {
        val fields = JSONObject(SyncCrypto.encryptToEnvelope("secret", "pw"))
        val ct = decode(fields.getString("ct"))
        ct[ct.size - 1] = (ct[ct.size - 1].toInt() xor 0x01).toByte()
        fields.put("ct", Base64.getEncoder().encodeToString(ct))
        assertThrows(SyncCryptoError::class.java) {
            SyncCrypto.decryptEnvelope(fields.toString(), "pw")
        }
    }

    @Test
    fun `rejects non-envelope and truncated blobs`() {
        listOf(
            "not json",
            """{"v":2,"kdf":"pbkdf2-sha256"}""",
            "[]",
            """{"v":1,"kdf":"pbkdf2-sha256","iter":1}""",
        ).forEach { blob ->
            assertThrows(
                "expected $blob to be rejected",
                SyncCryptoError::class.java,
            ) { SyncCrypto.decryptEnvelope(blob, "pw") }
        }
    }

    @Test
    fun `rejects a salt of the wrong length`() {
        val fields = JSONObject(SyncCrypto.encryptToEnvelope("x", "pw"))
        fields.put("salt", Base64.getEncoder().encodeToString(ByteArray(8)))
        assertThrows(SyncCryptoError::class.java) {
            SyncCrypto.decryptEnvelope(fields.toString(), "pw")
        }
    }

    @Test
    fun `rejects an IV of the wrong length`() {
        val fields = JSONObject(SyncCrypto.encryptToEnvelope("x", "pw"))
        fields.put("iv", Base64.getEncoder().encodeToString(ByteArray(8)))
        assertThrows(SyncCryptoError::class.java) {
            SyncCrypto.decryptEnvelope(fields.toString(), "pw")
        }
    }

    @Test
    fun `rejects a ciphertext shorter than the auth tag`() {
        val fields = JSONObject(SyncCrypto.encryptToEnvelope("x", "pw"))
        fields.put("ct", Base64.getEncoder().encodeToString(ByteArray(8)))
        assertThrows(SyncCryptoError::class.java) {
            SyncCrypto.decryptEnvelope(fields.toString(), "pw")
        }
    }

    @Test
    fun `bounds the blob-controlled iteration count`() {
        // The iteration count arrives INSIDE the attacker-supplied blob and
        // feeds PBKDF2's loop. Unbounded, a hostile 500-million-iteration
        // header is a denial of service against the phone that reads it.
        val fields = JSONObject(SyncCrypto.encryptToEnvelope("x", "pw"))
        fields.put("iter", 500_000_000)
        val error = assertThrows(SyncCryptoError::class.java) {
            SyncCrypto.decryptEnvelope(fields.toString(), "pw")
        }
        assertEquals("envelope iteration count is out of range", error.message)
    }

    @Test
    fun `rejects a non-base64 field`() {
        val fields = JSONObject(SyncCrypto.encryptToEnvelope("x", "pw"))
        fields.put("salt", "not base64 !!!")
        assertThrows(SyncCryptoError::class.java) {
            SyncCrypto.decryptEnvelope(fields.toString(), "pw")
        }
    }

    @Test
    fun `round-trips multi-byte plaintext and passphrase`() {
        val text = """{"hosts":[{"name":" bäckerei","hostname":"höfn.internal"}]}"""
        assertEquals(text, SyncCrypto.decryptEnvelope(SyncCrypto.encryptToEnvelope(text, "pässword"), "pässword"))
    }

    @Test
    fun `refuses an empty passphrase in both directions`() {
        assertThrows(SyncCryptoError::class.java) { SyncCrypto.encryptToEnvelope("x", "") }
        val envelope = SyncCrypto.encryptToEnvelope("x", "pw")
        assertThrows(SyncCryptoError::class.java) { SyncCrypto.decryptEnvelope(envelope, "") }
    }

    /**
     * The interoperability assertion. This envelope was produced by Node with
     * the same `pbkdf2Sync` / `aes-256-gcm` calls `SyncCrypto.ts` makes — i.e.
     * it is what the DESKTOP app would have uploaded. If the Android port's KDF,
     * cipher, tag placement, base64 or header parsing drifted by one byte, this
     * is the test that fails, and it is the only one that can.
     */
    @Test
    fun `decrypts an envelope written by the desktop app`() {
        val plaintext = SyncCrypto.decryptEnvelope(DESKTOP_ENVELOPE, DESKTOP_PASSPHRASE)
        assertEquals(DESKTOP_PLAINTEXT, plaintext)

        // And the payload it carries parses into the model this client uses,
        // which is the property that makes the two clients one account.
        val hosts = parseSyncPayload(plaintext)
        assertEquals(listOf("hetzner", "bäckerei"), hosts.map { it.name })
        assertEquals("135.181.114.209", hosts[0].hostname)
        assertEquals(2222, hosts[1].port)
    }

    /** Our own writes must be readable by the same reader, at full strength. */
    @Test
    fun `an envelope this client writes uses the desktop parameters`() {
        val fields = JSONObject(SyncCrypto.encryptToEnvelope(DESKTOP_PLAINTEXT, DESKTOP_PASSPHRASE))
        assertEquals(600_000, fields.getInt("iter"))
        assertEquals("pbkdf2-sha256", fields.getString("kdf"))
        assertEquals(1, fields.getInt("v"))
        assertEquals(
            setOf("v", "kdf", "iter", "salt", "iv", "ct"),
            fields.keys().asSequence().toSet(),
        )
    }

    /**
     * Published PBKDF2-HMAC-SHA256 vectors (the SHA-256 counterparts of
     * RFC 6070's SHA-1 set, as used by RFC 7914's test suite). These pin the
     * hand-rolled derivation to the same function Node's `pbkdf2Sync(..., 'sha256')`
     * computes, independently of any round-trip.
     */
    @Test
    fun `pbkdf2 matches the published SHA-256 vectors`() {
        assertEquals(
            "120fb6cffcf8b32c43e7225256c4f837a86548c92ccc35480805987cb70be17b",
            hex(SyncCrypto.pbkdf2HmacSha256(ascii("password"), ascii("salt"), 1, 32)),
        )
        assertEquals(
            "ae4d0c95af6b46d32d0adff928f06dd02a303f8ef3c251dfd6e2d85a95474c43",
            hex(SyncCrypto.pbkdf2HmacSha256(ascii("password"), ascii("salt"), 2, 32)),
        )
        assertEquals(
            "c5e478d59288c841aa530db6845c4c8d962893a001ce4e11a4963873aa98134a",
            hex(SyncCrypto.pbkdf2HmacSha256(ascii("password"), ascii("salt"), 4096, 32)),
        )
    }

    /** A key longer than one HMAC block exercises the multi-block loop. */
    @Test
    fun `pbkdf2 derives multi-block keys`() {
        assertEquals(
            "348c89dbcbd32b2f32d814b8116e84cf2b17347ebc1800181c4e2a1fb8dd53e1c635518c7dac47e9",
            hex(
                SyncCrypto.pbkdf2HmacSha256(
                    ascii("passwordPASSWORDpassword"),
                    ascii("saltSALTsaltSALTsaltSALTsaltSALTsalt"),
                    4096,
                    40,
                ),
            ),
        )
    }

    /**
     * A non-ASCII passphrase is the case a `PBEKeySpec`-based derivation gets
     * wrong: derived over UTF-8 bytes it agrees with Node, derived over UTF-16
     * or truncated chars it does not. Pinned against the value Node computes.
     */
    @Test
    fun `pbkdf2 derives a non-ASCII passphrase over UTF-8 bytes`() {
        assertEquals(
            hex(SyncCrypto.pbkdf2HmacSha256("pässword".toByteArray(StandardCharsets.UTF_8), ascii("salt"), 1000, 32)),
            hex(SyncCrypto.pbkdf2HmacSha256(byteArrayOf(112, -61, -92, 115, 115, 119, 111, 114, 100), ascii("salt"), 1000, 32)),
        )
    }

    private fun decode(value: String): ByteArray = Base64.getDecoder().decode(value)

    private fun ascii(value: String): ByteArray = value.toByteArray(StandardCharsets.UTF_8)

    private fun hex(bytes: ByteArray): String = bytes.joinToString("") { "%02x".format(it) }

    private companion object {
        const val DESKTOP_PASSPHRASE = "correct horse battery staple"

        const val DESKTOP_PLAINTEXT =
            """{"hosts":[{"name":"hetzner","hostname":"135.181.114.209","port":22,"user":"alexey"},""" +
                """{"name":"bäckerei","hostname":"höfn.internal","port":2222,"user":"root"}]}"""

        /**
         * Generated with Node 24 by replaying `SyncCrypto.ts`'s `encryptToEnvelope`
         * verbatim (`pbkdf2Sync(pass, salt, 600000, 32, 'sha256')`,
         * `createCipheriv('aes-256-gcm', …)`, `getAuthTag()` appended). Do not
         * regenerate it to make a change pass — it is the desktop app's output,
         * and the point is that this client can still read it.
         */
        const val DESKTOP_ENVELOPE =
            """{"v":1,"kdf":"pbkdf2-sha256","iter":600000,"salt":"pqH7wTMSdf45pMlYo0Tfpw==",""" +
                """"iv":"/hOH2hHO8BXuAVIP","ct":"o4m6kdyYvsiPjWDpp4ZihqDTmD9HAutBJLPbatZiS7rw4hGb8yQRd8Oygu""" +
                """M5BTorSLja73RKmMbodf0qDOEVFFsdmGKMdqi4QKcQEr1l1ma2XwlQvCL9Bsko08gvH6FGFCdEW5id4dlT95pCu0AN""" +
                """yLaR8zftF3v498aBuI/HvqAAAKVmwyQHrtF+GEDV/MwZnRn8KmHjxElOtsegXqZ5MA+48hIhZzMecMwBNLNVz/4="}"""
    }
}
