package com.pocketshell.core.storage.dao

import androidx.room.Dao
import androidx.room.Insert
import androidx.room.Query
import com.pocketshell.core.storage.entity.AiApiCallEntry
import kotlinx.coroutines.flow.Flow

/**
 * DAO for the client-side AI API call log (issue #181). Reads stream as a
 * [Flow] so the costs screen ViewModel can collect-and-aggregate without
 * polling. Inserts are blocking-suspend at the call site — the Whisper
 * client logs synchronously after each successful round-trip so a crash
 * between "HTTP returned 200" and "row inserted" can lose at most one
 * call. That trade-off is documented in the entity KDoc.
 *
 * Aggregates (sum over a time window) are computed in Kotlin from the
 * full `getAll` flow rather than in SQL: the table is tiny (a few rows
 * per session, weeks worth of history) and Compose-driven recompositions
 * are easier when one [Flow] feeds the whole screen.
 */
@Dao
interface AiApiCallLogDao {

    /**
     * Stream every logged call, newest first. Used by the costs screen to
     * render the "Recent calls" list and to compute the lifetime / today /
     * week / month totals client-side.
     */
    @Query("SELECT * FROM ai_api_call_log ORDER BY timestampMillis DESC")
    fun getAll(): Flow<List<AiApiCallEntry>>

    /**
     * Stream every logged call newer than [sinceMillis], newest first.
     * Kept on the DAO so the ViewModel can swap between "everything" and
     * "last 30 days" without re-doing the filter in Kotlin if the table
     * ever grows past comfortable RAM size. Not used by the issue #181
     * UI today; provided for forward-compat.
     */
    @Query("SELECT * FROM ai_api_call_log WHERE timestampMillis >= :sinceMillis ORDER BY timestampMillis DESC")
    fun getSince(sinceMillis: Long): Flow<List<AiApiCallEntry>>

    /**
     * Insert a single call. Returns the autogenerated id so callers that
     * need to attach diagnostics after-the-fact (a future "what was this
     * call's request id" follow-up) have a handle.
     */
    @Insert
    suspend fun insert(entry: AiApiCallEntry): Long

    /**
     * Wipe the log. Surfaced by the costs screen's "Clear log" affordance
     * (with a confirmation dialog). Historical pricing snapshots are lost
     * by design: the user asked for them gone.
     */
    @Query("DELETE FROM ai_api_call_log")
    suspend fun deleteAll()
}
